version: '3.8'
services:
  backend:
    build: .
    command: bash -c "alembic upgrade head && flask --app src/main run --host=0.0.0.0"
    environment:
      DB_HOST: "db"
    env_file:
      - .env
    ports: 
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kanban_network

  db:
    extends:
      file: infra.yml
      service: db
    networks:
      - kanban_network

networks:
  kanban_network: