"""Create first to do card table

Revision ID: 48b9b7400341
Revises: 94bf4550f6ef
Create Date: 2025-01-20 19:53:21.792653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b9b7400341'
down_revision: Union[str, None] = '94bf4550f6ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('to_do_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('sector', sa.String(length=250), nullable=True),
    sa.Column('user_creator_id', sa.Integer(), nullable=False),
    sa.Column('user_responsible_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=250), nullable=False, default="BACKLOG"),
    sa.Column('priority', sa.String(length=250), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('image', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(('user_creator_id',), ['users.id']),
    sa.ForeignKeyConstraint(('user_responsible_id',), ['users.id']),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('to_do_cards')
    # ### end Alembic commands ###